### ISSUE TITLE
Add S3 Plugin

### ISSUE THREAD

**Issue by Nfrederiksen** [Eyevinn/hls-pull-push#13]
Implement an S3 Bucket Plugin.

This plugin might need some extensions to the core of hls-pull-push as:
- if it is going to use `@eyevinn/iaf-plugin-aws-s3`, then a winston logger is required as input. some changes to the current logger interface need to be changed
- a segment deletion function needs to be implemented and hls-pull-push needs to add logic for using said function if provided.

**Comment by birme** [comment]
I am not sure requiring a winston logger is the right way to go to be honest. We should define a simpler Logger interface that could be implemented either with Winston as a logger or just a simple console log.

**Comment by Nfrederiksen** [comment]
> I am not sure requiring a winston logger is the right way to go to be honest. We should define a simpler Logger interface that could be implemented either with Winston as a logger or just a simple console log. Similar to how a logger is provided to the hls pull push instance via the ILogger interface.

@birme, I see, so you are suggesting that `@eyevinn/iaf-plugin-aws-s3`  should be updated and make use of a similar ILogger interface

**Comment by birme** [comment]
> > I am not sure requiring a winston logger is the right way to go to be honest. We should define a simpler Logger interface that could be implemented either with Winston as a logger or just a simple console log. Similar to how a logger is provided to the hls pull push instance via the ILogger interface.
> 
> @birme, I see, so you are suggesting that `@eyevinn/iaf-plugin-aws-s3` should be updated and make use of a similar ILogger interface

Yes, and also update the @types definitions. I think @oscnord could assist with that. And we need to consider the semantic versioning around this as this might be a breaking api change.

**Comment by Nfrederiksen** [comment]
will do
