### ISSUE TITLE
Insert SCTE-35 Messages in Manifest to Communicate Adbreaks to MediaPackage

### ISSUE THREAD

**Issue by Nfrederiksen** [Eyevinn/hls-pull-push#3]
MediaPackage will add Ad breaks and related tags to the output streams, based on the input stream's SCTE-35 messages. 
Supported SCTE-35 messages are documented here: https://docs.aws.amazon.com/mediapackage/latest/ug/scte.html

Currently, no SCTE-35 messages are included in `hls-pull-push`'s uploaded manifests.

We need to add SCTE-35 messages based on the original Ad metadata and generate an updated manifest.
Perhaps, we need to build a separate function to generate a manifest, instead of reusing the function `GenerateMediaM3U8(...)`. 
That way we don't need to make another update to `eyevinn/hls-recorder`

**Comment by birme** [comment]
I think the pull/push should only ensure to pass-through. It should be the source to accommodate for this, for example the VOD2Live channel engine.
